export const WORKOUTS_LOADING = "WORKOUTS_LOADING";
export const ADD_WORKOUTS = "ADD_WORKOUTS";
export const WORKOUTS_FAILED = "WORKOUTS_FAILED";

export const ADD_EXERCISE = "ADD_EXERCISE";
export const ADD_EXERCISES = "ADD_EXERCISES";
export const EXERCISE_FAILED = "EXERCISE_FAILED";
export const EXERCISES_FAILED = "EXERCISES_FAILED";

export const MEALS_LOADING = "MEALS_LOADING";
export const ADD_MEALS = "ADD_MEALS";
export const MEALS_FAILED = "MEALS_FAILED";

export const ADD_FOOD = "ADD_FOOD";
export const FOOD_FAILED = "FOOD_FAILED";

export const WEIGHTS_LOADING = "WEIGHTS_LOADING";
export const ADD_WEIGHTS = "ADD_WEIGHTS";
export const WEIGHTS_FAILED = "WEIGHTS_FAILED";

export const ADD_MORNING_WEIGHT = "ADD_MORNING_WEIGHT";
export const ADD_NIGHT_WEIGHT = "ADD_NIGHT_WEIGHT";
export const MORNING_WEIGHT_FAILED = "MORNING_WEIGHT_FAILED";
export const NIGHT_WEIGHT_FAILED = "NIGHT_WEIGHT_FAILED";
